name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USER }}
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        script: |
          cd ~/telegrambot
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          pkill -f "python3 main.py" || true
          sleep 2
          nohup python3 main.py > bot.log 2>&1 &
          echo "✅ Bot güncellendi ve başlatıldı!"